### ISSUE TITLE
Argument to write to a custom file?

### ISSUE THREAD

**Issue by maurelian** [vshotarov/haskell-fidenza#1]
It looks like currently you always just write to Fidenza.png.

It'd be great if you could specify the filename to write to.

**Comment by vshotarov** [comment]
This is an excellent example of how getting used to a broken interface makes you forget how broken it is. Thanks for flagging it up!

I've added the `--outFile` argument in f6bc7f329e3620afa11580406df5e589e582ca12 .

**Comment by maurelian** [comment]
Just seeing this now, thank you!
